### ISSUE TITLE
"New Folder" Subfolder on copy_fs

### ISSUE THREAD

**Issue by OzzieIsaacs** [rkhwaja/fs.googledrivefs#46] opened 2020-09-09 17:08 UTC
I'm trying to copy/upload a local folder to my googledrive via fs.googledrivefs with the following code:
```
from google.oauth2.credentials import Credentials
from fs.googledrivefs import GoogleDriveFS
from fs.osfs import OSFS
from fs.copy import copy_fs
import json
import os

# path on localdrive with one file in it
test_path = ...

# load necessary gdrive information
with open(os.path.join(base_path, 'files', 'gdrive_credentials'), 'r') as f:
    fs_content = f.read()
tokens = json.loads(fs_content)


credentials = Credentials(tokens['access_token'],
                          refresh_token=tokens['refresh_token'],
                          token_uri="https://www.googleapis.com/oauth2/v4/token",
                          client_id=tokens['client_id'],
                          client_secret=tokens['client_secret'])
fs = GoogleDriveFS(credentials=credentials)

# Create new subfolder on gdrive
fs.makedir('test')
info = fs.getinfo('test')
root_id = info.raw['sharing']['id']
#upload file from local drive
copy_fs(OSFS(test_path), GoogleDriveFS(credentials=credentials, rootId=root_id))
fs.close()
```
After doing so, the 'test' folder has an subfolder named 'New Folder', which is definitely not on the local drive.
![grafik](https://user-images.githubusercontent.com/6438895/92629990-6a12f200-f2cf-11ea-97c5-a692baa8943c.png)
![grafik](https://user-images.githubusercontent.com/6438895/92630044-7c8d2b80-f2cf-11ea-9e6c-118f5cc0e02c.png)

I'm using Linux Mint 20 with python 3.8
![grafik](https://user-images.githubusercontent.com/6438895/92631459-ae06f680-f2d1-11ea-90b0-97e26a5ab89f.png)

And one question: Is there an easier way of selecting the destination folder on the googledrive than by searching for the rootId and passing it to GoogleDriveFS?

**Comment by rkhwaja** [comment] 2020-09-09 22:52
The root_id argument was recently added and, as I understand it, it's used with GCP credentials.

It looks like you're using personal OAUTH credentials so you can do:

```
fs = GoogleDriveFS(credentials=credentials)

testDir = fs.makedir('test')

copy_fs(OSFS(test_path), testDir)
```

**Comment by OzzieIsaacs** [comment] 2020-09-10 08:22
Thank you for the answer, now the left open topic is the bug with the additional folder

**Comment by rkhwaja** [comment] 2020-09-11 00:51
Do you get the "New Folder" problem with the above code? If not, then I think that the problem is specific to using the rootId parameter, which is @msb's feature.

**Comment by OzzieIsaacs** [comment] 2020-09-11 17:36
With my original code (the one above) I get the subfolder, with your proposal the folder isn't showing up. Seems indeed to be a problem in conjunction with the roodId parameter.

**Comment by rkhwaja** [comment] 2023-05-07 19:47
Closing because no one is supporting the rootId code path

**Closed by rkhwaja** 2023-05-07 19:47 UTC
Labels: bug
